<a href="https://colab.research.google.com/github/mariodac/7DaysOfCode_Python_pandas/blob/main/intro_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays

In [29]:
import numpy as np

In [30]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [31]:
print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [32]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [33]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
print(array[0])

1


In [35]:
array[0] = 10
print(array)

[10  2  3  4  5  6]


# Matrizes

In [36]:
matriz_zero = np.zeros((5, 3))
print(matriz_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Notas de alunos

In [37]:
lista_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(lista_notas)
print(notas)
print('Máximo', notas.max())
print('Mínimo', notas.min())
print('Desvio Padrão', notas.std())
print('Média', notas.mean())
print('Posição menor', notas.argmin())
print('Posição maior', notas.argmax())

[9.8 5.6 7.8 9.1 6.5]
Máximo 9.8
Mínimo 5.6
Desvio Padrão 1.5628179676469045
Média 7.76
Posição menor 1
Posição maior 0


Escreva um programa que peça para o usuário digitar 10 notas de alunos, e realize algumas operações com esses dados

In [48]:
notas = []
for index in range(10):
    nota = float(input(f'Digite a nota #{index+1} do aluno: '))
    notas.append(nota)5
array_notas = np.array(notas)
print('Notas digitadas', array_notas)
print(f'Maior nota {array_notas.max()} e sua posição é {array_notas.argmax()}')
print(f'Maior nota {array_notas.min()} e sua posição é {array_notas.argmin()}')
print(f'Desvio Padrão {array_notas.std()}')
print(f'Média {array_notas.mean()}')

Digite a nota #1 do aluno: 1
Digite a nota #2 do aluno: 2
Digite a nota #3 do aluno: 3
Digite a nota #4 do aluno: 4
Digite a nota #5 do aluno: 5
Digite a nota #6 do aluno: 6
Digite a nota #7 do aluno: 74
Digite a nota #8 do aluno: 5
Digite a nota #9 do aluno: 6
Digite a nota #10 do aluno: 10
Notas digitadas [ 1.  2.  3.  4.  5.  6. 74.  5.  6. 10.]
Maior nota 74.0 e sua posição é 6
Maior nota 1.0 e sua posição é 0
Desvio Padrão 20.934182573007238
Média 11.6
